//关于登录的actionTypes
export const USER_LOGIN_START="USER/LOGIN/START";
export const USER_LOGIN_SUCCESS="USER/LOGIN/SUCCESS";
export const USER_LOGIN_FAIL="USER/LOGIN/FAIL";
export const USER_LOGIN_BEFORE_SUCCESS="USER/LOGIN/BEFORE/SUCCESS";
//关于注册的actionTypes
export const USER_REGISTER_START="USER/REGISTER/START";
export const USER_REGISTER_BEFORE_SUCCESS="USER/REGISTER/BEFORE/SUCCESS";
export const USER_REGISTER_SUCCESS="USER/REGISTER/SUCCESS";;
export const USER_REGISTER_FAIL="USER/REGISTER/FAIL";
//关于注销的actionTypes
export const USER_LOGOUT_START="USER/LOGOUT/START";
export const USER_LOGOUT_SUCCESS="USER/LOGOUT/SUCCESS";
export const USER_LOGOUT_FAIL="USER/LOGOUT/FAIL";
//关于验证邮箱的actionTypes
export const USER_VERIFY_EMAIL_START="USER/VERIFY/EMAIL/START";
export const USER_VERIFY_EMAIL_BEFORE_SUCCESS="USER/VERIFY/EMAIL/BEFORE/SUCCESS";
export const USER_VERIFY_EMAIL_SUCCESS="USER/VERIFY/EMAIL/SUCCESS";;
export const USER_VERIFY_EMAIL_FAIL="USER/VERIFY/EMAIL/FAIL";