//定义login状态
export const LOGIN_STATUS_START="LOGIN/STATUS/START";
export const LOGIN_STATUS_BEFORE_SUCCESS="LOGIN/STATUS/BEFORE/SUCCESS";
export const LOGIN_STATUS_SUCCESS="LOGIN/STATUS/SUCCESS";
export const LOGIN_STATUS_FAIL="LOGIN/STATUS/FAIL";
export const LOGIN_STATUS_NOT_START="LOGIN/STATUS/NOT/START";
//定义logout状态
export const LOGOUT_STATUS_START="LOGOUT/STATUS/START";
export const LOGOUT_STATUS_SUCCESS="LOGOUT/STATUS/SUCCESS";
export const LOGOUT_STATUS_FAIL="LOGOUT/STATUS/FAIL";
//定义register状态
export const REGISTER_STATUS_START="REGISTER/STATUS/START";
export const REGISTER_STATUS_BEFORE_SUCCESS="REGISTER/STATUS/BEFORE/SUCCESS";
export const REGISTER_STATUS_SUCCESS="REGISTER/STATUS/SUCCESS";
export const REGISTER_STATUS_FAIL="REGISTER/STATUS/FAIL";